version: '2'
services:
  web:
    image: nginx:1.13
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
  php:
    image: php:8.0.22-fpm
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./www:/usr/share/nginx/html
  composer:
    image: composer:1.5
    container_name: composer
