on:
  push:
    branches:
      - prod
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.zhp.com.br
        username: gdeploy@zhp.com.br
        password: ${{ secrets.ftp_password }}
        local-dir: ./www/build/
        server-dir: /public_html/ztp/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.well-known
          **/.well-known/**
          ./cache
          ./cache/**
          ./service
          ./service/**
          ./assets
          ./assets/**

    - name: 📂 Sync Service files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.zhp.com.br
        username: gdeploy@zhp.com.br
        password: ${{ secrets.ftp_password }}
        local-dir: ./www/service/
        server-dir: /public_html/ztp/service/       
        exclude: |
          **/.git*
          **/.git*/**
          *.json
          *.json**
